# MAIN
model_name: 'GAN_BiLSTM_30'

n_epochs: 30
batch_size: 16
validation_batch_size: 16

learning_rate: 0.001
shuffle: False
len_input: 150

train_dir: './INPUT/curve_npy'
valid_dir: './INPUT/curve_npy_valid'
test_dir: './INPUT/curve_npy_test'
processed_test_dir: './INPUT/processed_test/'
pic_output_dir: './OUTPUT/pic_output/'
error_dir: './OUTPUT/error_output/'
# GAN HYPERPARAMETERS
save_discriminator: True
# weight for Imputer Loss in partially adversarial training: [ MAE_Loss * w + GAN_Loss * (1-w) ]
loss_weight: 0.05
# ratio of total NaN's at each deterioration
# what value to be fed instead of NaN
placeholder_value: 0.5
# curves = ['GR','SP','RT','AC','SH','POR','PERM','SW','DEPTH']
input_num: 9
curve_code: 3